# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
zh:
 languageCode: zh-Hans
 contentDir: content/zh
 title: 蕴哲的个人网站
 params:
   description: Site description in Chinese...
 menu:
  - name: 关于
    url: '#about'
    weight: 10
  - name: 经历
    url: '#experience'
    weight: 20
  - name: 论文
    url: '#publications'
    weight: 30
  - name: 项目
    url: '#projects'
    weight: 40
  - name: 文章
    url: '#posts'
    weight: 50
  # - name: Talks
  #   url: '#talks'
  #   weight: 40
  - name: 联系
    url: '#contact'
    weight: 60
